### ISSUE TITLE
No relevant typo

### ISSUE THREAD

**Issue by miljan-aleksic** [cometchat-pro/.github#1]
### Describe the problem

There is a small typo in the code that doesn't affect anything but this is a good moment to fix it.

Affected File: CometChat.d.ts
Affected Line: 1509

It should state `MessageConstants` instead of `MessageConstatnts`;

I didn't rise a PR directly as per the Contributing Guidelines, but I can do so.

**Comment by paarthsabharwal** [comment]
Hi @miljan-aleksic, 
Thank you for sharing this.

We have flagged this for our technical team to investigate and do the necessary corrections if applicable.
Thanks again for notifying us. 😊

**Comment by mayur-bhandari** [comment]
Hello @miljan-aleksic ,

Thank you for pointing this out. We will make the necessary changes in the next release. But just wanted to let you know that this is should not cause any issues in using the SDK as the Messages Constants are exported as follows,

- CometChat.MESSAGE_TYPE {enum}
- CometChat.CATEGORY_MESSAGE {string}
- CometChat.CATEGORY_ACTION {string}
- CometChat.CATEGORY_CALL {string}
- CometChat.CATEGORY_CUSTOM {string}
- CometChat.RECEIVER_TYPE {enum}

Hope this helps.
